// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6IrpxDo4ejG4FyJq8scqbZDKz7ZwCr_o',
    appId: '1:962144233672:web:b351945a93182b14875dfd',
    messagingSenderId: '962144233672',
    projectId: 'instant-cash-2941d',
    authDomain: 'instant-cash-2941d.firebaseapp.com',
    storageBucket: 'instant-cash-2941d.appspot.com',
    measurementId: 'G-SVW8KR7B1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgoqGvo7Nfto-CGZXewjpzJprIPM5IeM',
    appId: '1:962144233672:android:22df966c93260baf875dfd',
    messagingSenderId: '962144233672',
    projectId: 'instant-cash-2941d',
    storageBucket: 'instant-cash-2941d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqStWA8UH9XftMgKUK2ZhxUYywuk8-27c',
    appId: '1:962144233672:ios:650bccc337c750ae875dfd',
    messagingSenderId: '962144233672',
    projectId: 'instant-cash-2941d',
    storageBucket: 'instant-cash-2941d.appspot.com',
    iosBundleId: 'com.example.instantCash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqStWA8UH9XftMgKUK2ZhxUYywuk8-27c',
    appId: '1:962144233672:ios:650bccc337c750ae875dfd',
    messagingSenderId: '962144233672',
    projectId: 'instant-cash-2941d',
    storageBucket: 'instant-cash-2941d.appspot.com',
    iosBundleId: 'com.example.instantCash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6IrpxDo4ejG4FyJq8scqbZDKz7ZwCr_o',
    appId: '1:962144233672:web:0c8bce6e36823693875dfd',
    messagingSenderId: '962144233672',
    projectId: 'instant-cash-2941d',
    authDomain: 'instant-cash-2941d.firebaseapp.com',
    storageBucket: 'instant-cash-2941d.appspot.com',
    measurementId: 'G-CV54NFK64D',
  );
}
